# SPDX-FileCopyrightText: 2009 Fermi Research Alliance, LLC
# SPDX-License-Identifier: Apache-2.0

name: Notify New Pull Request
on:
  pull_request:
    types: ready_for_review

jobs:
  notify_new_pr:
    runs-on: ubuntu-latest
    name: A job to notify when a new pull request is opened
    steps:
      - name: Echo PR Info
        shell: bash
        run: |
          PR_NUM="${{ github.event.pull_request.number }}"
          PR_TITLE="${{ github.event.pull_request.title }}"
          PR_HTML_URL="${{ github.event.pull_request.html_url }}"
          echo "A new pull request has been opened! [${PR_TITLE}](${PR_HTML_URL})"
